net: inet_connection_sock: Fix build error with older timer API
The commit f9544eee41e7 ("tcp/dccp: Don't use timer_pending()
in reqsk_queue_unlink().") uses timer_delete_sync() which is not available
in older kernel versions, causing a build error:

  net/ipv4/inet_connection_sock.c:720:21: error: implicit declaration of
  function 'timer_delete_sync' [-Werror,-Wimplicit-function-declaration]

Replace timer_delete_sync() with del_timer_sync() which provides the same
functionality.

Fixes: f9544eee41e7 ("tcp/dccp: Don't use timer_pending() in reqsk_queue_unlink().")

Change-Id: I4c1f2f17ef87525437dbe5d91db6bb0c2ec11908
(cherry picked from commit a254db5c68a87bc22076e73fcf140e4f22505e5a)
Signed-off-by: 1tovgar <tovgar@proton.me>