Revert "[ALPS05284571] mm: avoid anon_vma use-after-free"
This reverts commit 7ef97ced8f3748c4172e2ba55532cdf16ce4dbbb.

Fixes "error: no member named 'private' in 'struct anon_vma'".

Signed-off-by: 1tovgar <tovgar@proton.me>